### ISSUE TITLE
Get empty object

### ISSUE THREAD

**Issue by kennyk65** [adamchainz/ec2-metadata#128]
Hi Adam,
I'm new to Python, so bear with me:  I'm trying to use your library to get the ec2 metadata when running on EC2.  But when I'm running locally, I need an 'empty' version of it that doesn't throw exceptions at me.  How do I do this?
thx,
k

**Comment by adamchainz** [comment]
Hi Kenny

Check out the code: https://github.com/adamchainz/ec2-metadata/blob/master/ec2_metadata.py#L26

The default object *is* "empty". When you access its attributes, it calls the EC2 metadata service to try and retrieve the data, and then it caches them - that's what the `@cached_property` decorator does. 

If you're seeing exceptions, I'm guessing they're to do with accessing the metadata service? (In future bug reports please remember to paste tracebacks!) Unfortunately the library is entirely based aruond accessing the service so if you use it outside of an EC2 instance it's going to fail like that. Issue #84 is around providing a test version of the objcet that has dummy values, which might be what you're looking for, I haven't implemented that though.

Closing this issue now since I don't think there's anything new to do here.

—Adam
