### ISSUE TITLE
support of AWS_EC2_METADATA_INSTANCE_ENDPOINT to create custom endpoint.

### ISSUE THREAD

**Issue by vikansal** [adamchainz/ec2-metadata#242]
AWS sdks support the custom endpoint in v2. This repo could do the same to make it at par. Something like this:

ec2_metadata.py:

import os
SERVICE_URL = os.getenv("AWS_EC2_METADATA_INSTANCE_ENDPOINT","http://169.254.169.254").strip("/") + "/latest/"

**Comment by adamchainz** [comment]
Can you point me to documentation of the SDK's supporting a custom metadata endpoint? Do they use that environment variable?

**Comment by kut** [comment]
Seems like the metadata endpoint is different for certain containers in AWS (most problematically ECS), see here: https://stackoverflow.com/a/57066174

The endpoint becomes `169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`, would be great either to support either this endpoint or allow custom endpoints per the original message above.

**Comment by adamchainz** [comment]
The credentials URI is different to the metadata instance. I can't find any mention in AWS docs about an `AWS_EC2_METADATA_INSTANCE_ENDPOINT` env var. There are also [no github code results](https://github.com/search?q=AWS_EC2_METADATA_INSTANCE_ENDPOINT&type=code).

If you can point to AWS docs about the metadata service running at a different URL, we can reopen the issue.

**Comment by briantist** [comment]
I would like to reopen this issue if possible. My use case is that my project uses `ec2-metadata` and I want to be able to run it locally on my machine. I can mock the metadata service with something like this https://github.com/aws/amazon-ec2-metadata-mock but I want to run the mock on its own port/address without having to specifically bind it to `169.254.169.254:80`, but since [the metadata service URL is hardcoded](https://github.com/adamchainz/ec2-metadata/blob/70d1ecdae9a86acaeb8005d353e0cfc53ffdf628/src/ec2_metadata/__init__.py#L84), I cannot easily do that.

I don't think this library should automatically use an environment variable as originally requested; the client project can read its own desired env var and pass the value in (or you could provide _opt-in_ support for such an env var), since libraries reading env vars can lead to some unexpected results for the projects that use them.

**Comment by adamchainz** [comment]
@briantist:

First, in general, please don’t comment on 2.5 year old issues, especially with a slightly different request. Just make a new one and reference the old one. That makes the conversation more comprehensible and avoids pinging people who probably don’t care.

Second, taking the service URL as a parameter in `__init__` seems like a reasonable change. Would you like to open a PR? Include docs, tests, and a changelog note. See previous PRs for examples of what to do.

**Comment by vikansal** [comment]
Here is the env reference in Go SDK - https://docs.aws.amazon.com/sdk-for-go/api/aws/ec2metadata/  (Overview section) and https://docs.aws.amazon.com/sdk-for-go/api/aws/session/ (Custom EC2 IMDS Endpoint section)

The actual env var is named AWS_EC2_METADATA_SERVICE_ENDPOINT
